new structure functionality for logo and favicon
pysal/logo pull request #6
Opened 2019-12-08 23:39 UTC by jGaboardi

This PR adds a directory containing the files (and certain produced files) for reproducibly creating the PySAL logo.

Files include:
  * `create_pysal_logo.py`
    * flexible functions for creating the PySAL logo and favicons with customizable
      * colors
      * text (or no text)
      * number of child/grandchild nodes
      * etc.
    * automatic file conversions and removal with `subprocess` calls

  * `pysal_logo.tex`
    * `.tex` file created within `create_pysal_logo.py`

* `pysal_logo.pdf` <-- where is this?
* `pysal_logo.png`
* `pysal_logo_favicon_*.png`

2019-12-08 23:41 UTC, jGaboardi commented
I wasn't sure about the origins of the PySAL logo and/or the origins of the initial `.tex` file for the logo. Is this documented anywhere? Or in someone's memory? I think it would be appropriate to list anyone who contributed to the over the lifetime of PySAL.

2019-12-08 23:41 UTC, jGaboardi commented
@sjsrey @knaaptime @weikang9009

2019-12-08 23:44 UTC, jGaboardi commented
Please tag any others of the team here.

2019-12-09 01:38 UTC, sjsrey commented
> I wasn't sure about the origins of the PySAL logo and/or the origins of the initial `.tex` file for the logo. Is this documented anywhere? Or in someone's memory? I think it would be appropriate to list anyone who contributed to the over the lifetime of PySAL.

The origins were for the 2007 article by Rey and Anselin. 

> I wasn't sure about the origins of the PySAL logo and/or the origins of the initial `.tex` file for the logo. Is this documented anywhere? Or in someone's memory? I think it would be appropriate to list anyone who contributed to the over the lifetime of PySAL.

The original logo and tex file were based on the 2007 RRS paper by Rey and Anselin.

2019-12-09 17:32 UTC, weikang9009 commented
When I tried to run `$ python create_pysal_logo.py`, it complains a font missing error:
![image](https://user-images.githubusercontent.com/7359284/70458259-9bbc0b80-1a66-11ea-93ec-c2d62352d8f8.png)

2019-12-09 17:55 UTC, jGaboardi commented
> When I tried to run $ python create_pysal_logo.py, it complains a font missing error:

Good catch. I'll push up font download instructions.

2019-12-13 22:21 UTC, weikang9009 requested changes

2019-12-13 22:21 UTC, weikang9009 commented on pysal_2-1_logo/create_pysal_logo.py
> +        info -- https://mplus-fonts.osdn.jp/about-en.html
The default font for generating the logo is "M+ 1mn". It might be useful to add a short sentence to remind the developers to install this font after downloading M+ fonts since there are more than 40 fonts in the downloaded folder.

2019-12-13 22:21 UTC, weikang9009 commented on pysal_2-1_logo/create_pysal_logo.py
> +_7_NODE_TEXT = [r"$\" + t + "$" for t in _7_NODE_TEXT]
I ran into syntax error (line 69) when running `python create_pysal_logo.py True` on my mac (python 3.7). Changing lines 68 and 69 to 
```
_7_NODE_TEXT = [r"$\theta$", r"$\gamma$", r"$\tau$", 
                r"$\lambda$", r"$\alpha$", r"$W$", r"$\rho$"]
```
resolves the issue and properly renders latex symbols as well as regular symbol `W`.

2019-12-13 23:36 UTC, weikang9009 approved these changes
Looks great! Thank you for this!

2019-12-14 00:03 UTC, jGaboardi commented
> Looks great! Thank you for this!

My pleasure! 😸

2019-12-14 01:10 UTC, knaaptime approved these changes

2019-12-18 18:39 UTC, knaaptime commented
can we start a new dev branch that we can PR into for each other's review, then we'll do a pr into master once we're satisfied?

2019-12-19 00:16 UTC, jGaboardi commented
Would it work to simply pull down this PR and add to it?

2019-12-19 00:22 UTC, knaaptime commented
yes, but then if i make changes that i want to share, you cant see them?

2019-12-19 01:09 UTC, jGaboardi commented
Why not simply push those changes back to this PR?

https://stackoverflow.com/a/5884825/8692996

2019-12-19 01:30 UTC, knaaptime commented
i'm good with that model if you prefer, just though a dev branch might be a bit more flexible

2019-12-19 01:40 UTC, jGaboardi commented
I'm good with flexible! How can we create a `dev` branch? I guess I'm just not understanding correctly.

2019-12-19 01:56 UTC, knaaptime commented
started a new [`dev`](https://github.com/pysal/logo/tree/dev) branch with your changes, so feel free to push straight to it. But to call each other's attention to changes, we can issue PRs against dev instead of master. As we decide on "official" changes, we'll merge them into master

2019-12-19 02:00 UTC, jGaboardi commented
Shall I close this PR then?

2019-12-19 02:07 UTC, knaaptime commented
👍

also i looove the new purple

2020-02-07 18:51 UTC, merged